name: Deploy to GitHub pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Clear gh-pages branch
        run: |
          git checkout --orphan temp-branch
          git add -A
          git commit -am "Clear gh-pages branch"
          git branch -D gh-pages
          git branch -m gh-pages
          git push -f origin gh-pages

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist

     
